baseURL = "https://bitsandwonder.com/"
languageCode = "en-us"
title = "Bits and Wonder"
theme = "PaperMod"

[params]
  description = "Exploring the stories behind everyday life"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "light"

  [params.homeInfoParams]
    Title = "Welcome to Bits and Wonder"
    Content = "Exploring the fascinating stories behind the things we do, say, and wonder about every day."

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20

[taxonomies]
  category = "categories"
  tag = "tags"
